import { StyleSheet } from "react-native";
import { useTheme } from "../../utils/useTheme";
import { responsiveFontSize, responsiveSpacing } from "../../utils/responsive";

export const getCardFormStyles = (theme: ReturnType<typeof useTheme>) =>
  StyleSheet.create({
    container: {
      flex: 1,
    },
    content: {
      paddingBottom: theme.spacing.xl * 2,
    },
    stickyHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingVertical: theme.spacing.md,
      marginBottom: theme.spacing.xs,
    },
    headerSpacer: {
      width: 40,
    },
    saveButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: theme.colors.accent,
      alignItems: "center",
      justifyContent: "center",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.2,
      shadowRadius: 8,
      elevation: 4,
    },
    saveButtonDisabled: {
      backgroundColor: theme.colors.surfaceTint,
      opacity: 0.5,
    },
    section: {
      marginBottom: theme.spacing.lg,
    },
    sectionTitle: {
      fontFamily: theme.font.bold,
      fontSize: responsiveFontSize(12),
      color: theme.colors.accent,
      textTransform: "uppercase",
      letterSpacing: 1.5,
      marginBottom: theme.spacing.md,
      marginLeft: 4,
    },
    field: {
      marginBottom: theme.spacing.lg,
    },
    label: {
      fontFamily: theme.font.bold,
      fontSize: responsiveFontSize(13),
      color: theme.colors.muted,
      marginBottom: theme.spacing.xs,
      marginLeft: 4,
    },
    inputWrapper: {
      backgroundColor: theme.colors.surfaceTint,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: theme.colors.outline,
      paddingHorizontal: 16,
      overflow: "hidden",
    },
    inputWrapperError: {
      borderColor: theme.colors.danger,
      backgroundColor: theme.colors.accentSoft,
    },
    notesWrapper: {
      paddingVertical: 12,
    },
    input: {
      paddingVertical: 14,
      color: theme.colors.ink,
      fontFamily: theme.font.regular,
      fontSize: responsiveFontSize(16),
    },
    cardNumberRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: theme.spacing.sm,
    },
    cardNumberInput: {
      flex: 1,
    },
    cardBrand: {
      width: responsiveSpacing(32),
      height: responsiveSpacing(24),
      borderRadius: 4,
      alignItems: "center",
      justifyContent: "center",
    },
    notesInput: {
      minHeight: 100,
      textAlignVertical: "top",
      paddingTop: 0,
    },
    tagsContainer: {
      minHeight: 44,
      paddingHorizontal: 4,
      marginTop: 4,
    },
    tagsFlow: {
      flexDirection: "row",
      flexWrap: "wrap",
      alignItems: "center",
      gap: 12,
    },
    tagChip: {
      flexDirection: "row",
      alignItems: "center",
      paddingVertical: 6,
      paddingHorizontal: 12,
      borderRadius: 20,
      gap: 6,
      borderWidth: 1,
    },
    tagChipText: {
      fontFamily: theme.font.regular,
      fontSize: responsiveFontSize(15),
      lineHeight: 18,
      includeFontPadding: false,
    },
    addTagButton: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: theme.colors.surfaceTint,
      paddingVertical: 8,
      paddingHorizontal: 14,
      borderRadius: 20,
      gap: 6,
      borderWidth: 1,
      borderColor: theme.colors.outline,
    },
    addTagButtonText: {
      fontFamily: theme.font.bold,
      fontSize: responsiveFontSize(14),
      color: theme.colors.accent,
      lineHeight: 18,
      includeFontPadding: false,
    },
    tagInputInline: {
      minWidth: 100,
      paddingVertical: 8,
      paddingHorizontal: 14,
      color: theme.colors.ink,
      fontFamily: theme.font.regular,
      fontSize: responsiveFontSize(15),
      borderRadius: 20,
      borderWidth: 1,
      includeFontPadding: false,
    },
    suggestions: {
      marginTop: 12,
      paddingTop: 12,
      borderTopWidth: 1,
      borderTopColor: theme.colors.outline,
    },
    suggestionItem: {
      paddingVertical: 6,
      paddingHorizontal: 12,
      borderRadius: 20,
      marginRight: 8,
      borderWidth: 1,
    },
    suggestionText: {
      fontFamily: theme.font.regular,
      fontSize: responsiveFontSize(13),
    },
    existingTags: {
      marginTop: theme.spacing.sm,
      gap: theme.spacing.xs,
      paddingHorizontal: 0,
    },
    existingTagsHeader: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 0,
    },
    existingTagsTitle: {
      fontFamily: theme.font.bold,
      fontSize: responsiveFontSize(13),
      letterSpacing: 0.2,
      color: theme.colors.muted,
    },
    existingTagsHint: {
      fontFamily: theme.font.regular,
      fontSize: responsiveFontSize(12),
      color: theme.colors.muted,
      opacity: 0.8,
    },
    existingTagsFlow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: theme.spacing.sm,
      paddingHorizontal: 0,
    },
    existingTagChip: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      paddingVertical: 7,
      paddingHorizontal: 12,
      borderRadius: 18,
      borderWidth: 1,
    },
    existingTagText: {
      fontFamily: theme.font.bold,
      fontSize: responsiveFontSize(14),
    },
    errorText: {
      marginTop: 6,
      marginLeft: 4,
      fontFamily: theme.font.regular,
      fontSize: responsiveFontSize(12.5),
      color: theme.colors.danger,
    },
    modalBackdrop: {
      flex: 1,
      justifyContent: "center",
      padding: theme.spacing.xl,
      backgroundColor: "rgba(0,0,0,0.5)",
    },
    modalSheet: {
      borderRadius: theme.radius.xl,
      backgroundColor: theme.colors.surface,
      padding: theme.spacing.xl,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.2,
      shadowRadius: 24,
      elevation: 10,
    },
    modalTitle: {
      fontFamily: theme.font.bold,
      color: theme.colors.ink,
      fontSize: responsiveFontSize(20),
      marginBottom: theme.spacing.sm,
      textAlign: "center",
    },
    modalBody: {
      fontFamily: theme.font.regular,
      color: theme.colors.muted,
      textAlign: "center",
      fontSize: responsiveFontSize(15),
      lineHeight: 22,
      marginBottom: theme.spacing.xl,
    },
    modalActions: {
      flexDirection: "row",
      gap: theme.spacing.md,
    },
    modalGhost: {
      flex: 1,
      borderRadius: theme.radius.md,
      paddingVertical: theme.spacing.md,
      alignItems: "center",
      backgroundColor: theme.colors.surfaceTint,
    },
    modalGhostText: {
      color: theme.colors.ink,
      fontFamily: theme.font.bold,
    },
    modalDanger: {
      flex: 1,
      borderRadius: theme.radius.md,
      paddingVertical: theme.spacing.md,
      alignItems: "center",
      backgroundColor: theme.colors.danger,
    },
    modalDangerText: {
      color: theme.colors.surface,
      fontFamily: theme.font.bold,
    },
  });
